### ISSUE TITLE
Looks like we are not excluding alleys

### ISSUE THREAD

**Issue by fgregg** [open-city/clearstreets-processing#11]
![screenshot from 2015-12-31 17 58 37](https://cloud.githubusercontent.com/assets/536941/12069180/4b6e7812-afe8-11e5-8aad-4db7ff2b62f6.png)

**Comment by fgregg** [comment]
@evz please add the lua file to the repo

**Comment by evz** [comment]
I'm just using this one: https://github.com/Project-OSRM/osrm-backend/blob/develop/profiles/car.lua

As I mentioned in [the issue](https://github.com/Project-OSRM/osrm-backend/issues/1852) I was experimenting with adding: 

```
service_tag_restricted = { ["parking_aisle"] = true, ["alley"] = true }
```

or:

```
service_tag_blacklist = { ["alley"] = true }
```

but haven't figured out what works.

**Comment by evz** [comment]
This should be fixed the next time we run.
